services:
  shear:
    image: shear:latest
    env_file: .env
    command: /app/shear
    restart: unless-stopped
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: "10m"