global:
  resolve_timeout: 5m

receivers:
  - name: 'slack'
    slack_configs:
      - api_url: $1
        channel: 'shear'
        send_resolved: false
        title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
        text: |
          *Alert:* {{ .CommonLabels.alertname }}
          *Summary:* {{ .CommonLabels.summary }}
          {{ range .Alerts }}
          *Instance:* {{ .Labels.instance }}
          *Fired At:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'slack'